name: Create and publish the blockbook's containers
on:
  push:
    branches: ['master']
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'tag for this image build'
        required: true
        default: 'latest'
    
jobs:
  build_blockbook: 
    runs-on: ubuntu-20.04

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: martinkey
          password: ${{ secrets.SECRET }}
      -
        name: Build and push latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gostartups/golang-rocksdb-zeromq:latest
      - 
        name: Build and push with Tag
        uses: docker/build-push-action@v2
        if: 
          ${{ github.event.input.image_tag != null }}
        with:
          push: true
          tags: gostartups/golang-rocksdb-zeromq:${{ github.event.inputs.image_tag }}
          
